# Site settings
author: Adam Duff
title: attr_accessor :adam
header-img: img/home-bg.png
email: j.adam.duff@gmail.com
copyright_name: Adam Duff
description: > # this means to ignore newlines until "baseurl:"
  Thoughts on development, learning, etc.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  jadamduff

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
